version: '3.1'

services:
  db:
    image: mariadb:10.2
    restart: on-failure
    ports:
      - "3308:3306"
    volumes:
      - ./db:/home/daniil/work/p_bot/aiogram/db-data
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: bot
      MYSQL_USER: rootw
      MYSQL_PASSWORD: root
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  adminer:
    image: adminer
    ports:
      - 8081:8080


